# Generated by Django 3.2.9 on 2022-01-26 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Using',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('contents', models.CharField(choices=[('T', 'Tea'), ('C', 'Coffee'), ('M', 'Milk'), ('W', 'Water'), ('A', 'Alcohol')], default='T', max_length=1)),
                ('cup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.cup')),
            ],
        ),
    ]
