# Generated by Django 3.2.9 on 2022-01-26 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_using'),
    ]

    operations = [
        migrations.RenameField(
            model_name='using',
            old_name='contents',
            new_name='content',
        ),
        migrations.AlterField(
            model_name='using',
            name='date',
            field=models.DateField(verbose_name='used date'),
        ),
    ]
