# Generated by Django 3.2.9 on 2022-01-27 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

		dependencies = [
				('main_app', '0004_alter_using_options'),
		]

		operations = [
				migrations.CreateModel(
						name='Toy',
						fields=[
								('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
								('name', models.CharField(max_length=50)),
								('color', models.CharField(max_length=20)),
						],
				),
				migrations.AddField(
						model_name='cup',
						name='toys',
						field=models.ManyToManyField(to='main_app.Toy'),
				),
		]
