# Generated by Django 3.2.9 on 2022-01-27 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20220127_0049'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Toy',
            new_name='Sticker',
        ),
        migrations.RemoveField(
            model_name='cup',
            name='toys',
        ),
        migrations.AddField(
            model_name='cup',
            name='stickers',
            field=models.ManyToManyField(to='main_app.Sticker'),
        ),
    ]
